name: Validate Metadata

on:
  pull_request:
    branches: [main]
    paths:
        - '**/modernization-metadata/**'

permissions:
  pull-requests: write

jobs:
  validate-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 #v5.6.0
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install requests PyGithub jsonschema

      - name: Validate metadata
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python scripts/validate_metadata.py
